services:
  nginx:
    image: nginx:stable
    container_name: nginx-shop
    ports:
      - "80:80"
    volumes:
      - ../app:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php
      - phpmyadmin

  php:
    container_name: php-shop
    build:
      context: ./php
    volumes:
      - ../app:/var/www/html
    working_dir: /var/www/html
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1

  mysql:
    image: mysql:8
    platform: linux/arm64
    container_name: mysql-shop
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sylius
      MYSQL_USER: sylius
      MYSQL_PASSWORD: sylius
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    container_name: phpmyadmin-shop
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - mysql
    expose:
      - 80

volumes:
  mysql-data:
